"""Shim: la lógica de MercadoPago ahora vive en libracore.db.mp."""
from libracore.db.mp import (  # noqa: F401
    get_mp_pago,
    create_mp_pago,
    get_mp_pago_by_id,
    get_mp_pagos_by_estado,
    get_mp_pagos_historial,
    update_mp_pago_estado,
    crear_alias_facturacion,
    get_alias_facturacion_by_cliente,
    eliminar_alias_facturacion,
    get_cliente_por_alias_pago,
    resolver_cliente_pago,
    get_mp_movimiento_by_mp_id,
    create_mp_movimiento,
    get_mp_movimiento_by_id,
    get_mp_movimientos_by_estado,
    get_mp_movimientos_historial,
    update_mp_movimiento_datos,
    update_mp_movimiento_estado,
    get_mp_pending_count,
    vincular_mp_pago_cliente,
)
